stats-server/config/routes.rb
StatsServer::Application.routes.draw do

  get "home/index"

  resources :submissions
  resources :os_statistics
  resources :installed_ports
  resources :categories, :only => [:index] do
    match '/ports/page/:page', :to => 'ports#index', :page => :page
    resources :ports, :only => [:index, :show]
  end

  match '/ports/page/:page', :to => 'ports#index', :page => :page
  resources :ports, :only => [:index, :search]
  match '/ports/search', :to => 'ports#search_generate', :as => :search_generate
  match '/ports/search/:criteria/:val/page/:page', :to => 'ports#search', :criteria => :criteria, :val => :val, :page => :page
  match '/ports/search/:criteria/:val', :to => 'ports#search', :criteria => :criteria, :val => :val, :as => :search

  root :to => 'home#index'
  match ':action' => 'static#:action'
end

stats-server/app/views/partials/_chart_draw.html.erb
<%# Set Defaults %>
<% drawtables_default = true %>
<% headers_default = true %>
<% chart_width_default = 700 %>
<% chart_height_default = 400 %>

<%# Check if locals have been passed to this partial %>
<%# Use them if available, otherwise use defaults %>

<%# Avoid nil objects  %>
<% if (defined? charts).nil? %>  
	<% charts = Hash.new %>
<% end %>

<%# Draw tables as well as visualizations? %>
<% if (defined? drawtables).nil? %>
	<% drawtables = drawtables_default %>
<% end %>

<%# Write headers? %>
<% if (defined? headers).nil? %>
	<% headers = headers_default %>
<% end %>

<%# Get chart width %>
<% if (defined? chart_width).nil? %>
	<% chart_width = chart_width_default %>
<% end %>

<%# Get chart height %>
<% if (defined? chart_height).nil? %>
	<% chart_height = chart_height_default %>
<% end %>

<%# Set visualization options %>
<% vis_options = {:width => chart_width, :height => chart_height, :pieHole => 0.4, :backgroundColor => '#ededed', :fontName => 'Helvetica', :html => {:class => "graph_chart"}} %>
<%# Set table options %>
<% tbl_options = {:width => 700, :html => {:class => "graph_chart"}} %>

<%# Draw charts %>
<% charts.each do |chart| %>
	<% title = controller.chart_title chart %>
	<% type = controller.chart_type chart %>

	<%# Set titles %>
	<!-- Chart title: <%= title %> -->
	<% local_vis_options = vis_options.merge({ :title => title }) %>
	<% local_tbl_options = tbl_options.merge({ :title => title }) %>

	<%# Anchor %>
	<a name=<%= chart %>> </a>
	<%# Title %>
	<% if headers %>
		<h3><%= title %></h3>
	<% end %>

	<% if not controller.dataset_empty? chart %>
		<%# Draw visualization %>
		<% visualization chart.to_s, type, local_vis_options do |viz| %>
			<% controller.populate_chart chart, viz %>
		<% end %>

		<% if drawtables %>
			<%# Draw table %>
			<% table = chart.to_s + "_table" %>
			<% visualization table, "Table", local_tbl_options do |viz| %>
				<% controller.populate_chart chart, viz %>
			<% end %>
		<% end %>
	<% else %>
		<p class="no-data">No data to display.</p>
	<% end %>  
<% end %>

stats-server/app/views/partials/_nav.html.erb
<div id="navigation">
  <dl>
    <dt>Getting Started</dt>
    <dd>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Installing MacPorts', install_path %></li>
        <li><%= link_to 'Available Ports', categories_path %></li>
        <li><%= link_to 'Documentation', $guide_url %></li>
        <li><%= link_to 'Support & Development', $trac_url %></li>
        <li><%= link_to 'Contact Us', contact_path %></li>
        <li><%= link_to 'News', "#{$trac_url}news" %></li>
      </ul>
    </dd>

    <dt>Shortcuts</dt>
      <dd>
        <ul>
          <li><%= link_to 'Available Downloads', $downloads_url %></li>
          <li><%= link_to 'MacPorts FAQ', "#{$trac_url}wiki/FAQ" %></li>
          <li><%= link_to 'Report a Bug', "#{$trac_url}newticket" %></li>
          <li><%= link_to 'Bug reporting Guidelines', "#{$trac_url}#project.tickets" %></li>
          <li><%= link_to 'Subversion Repository', $svn_url %></li>
          <li><%= link_to 'MacPorts Team', "#{$trac_url}wiki/MacPortsDevelopers" %></li>
          <li><%= link_to 'Becoming a Member', "#{$guide_url}#project.membership" %></li>
          <li><%= link_to 'Mac OS Forge', 'http://www.macosforge.org' %></li>
        </ul>
      </dd>
    </dl>
</div>

stats-server/app/views/partials/_port_search.html.erb
<div class="port-search">
	<h2>Search for Port Statistics</h2> 
	<p>
		<%= form_tag(search_generate_path, {:method => :get}) do %>
			<%= select_tag :criteria, options_for_select({"Software Title" => "name", "Category" => "categories", "Maintainer" => "maintainers", "variant" => "variants", "Platform" => "platforms"}) %>
			<%= text_field_tag :val, "", {:size => 40} %>
			<%= submit_tag "Search" %>
		<% end %>
	</p>
	<p>Or view the complete <%= link_to "port list (#{Port.count} ports)", ports_path %>. You can also <%= link_to "browse by category", categories_path %>.</p> 
</div>