stats-server/config/routes.rb
StatsServer::Application.routes.draw do

  get "home/index"

  resources :submissions
  resources :os_statistics
  resources :installed_ports
  resources :categories, :only => [:index] do
    match '/ports/page/:page', :to => 'ports#index', :page => :page
    resources :ports, :only => [:index, :show]
  end

  match '/ports/page/:page', :to => 'ports#index', :page => :page
  resources :ports, :only => [:index, :search]
  match '/ports/search', :to => 'ports#search_generate', :as => :search_generate
  match '/ports/search/:criteria/:val/page/:page', :to => 'ports#search', :criteria => :criteria, :val => :val, :page => :page
  match '/ports/search/:criteria/:val', :to => 'ports#search', :criteria => :criteria, :val => :val, :as => :search

  root :to => 'home#index'
  match ':action' => 'static#:action'
end

stats-server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>MacPorts Package Installation Statistics</title>
		<%= stylesheet_link_tag :all %>
		<%# javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
		<%= include_visualization_api %>
		<%= render_visualizations %>
	</head>
	<body>
		<h1>
			<a href="//www.macports.org/" title="The MacPorts Project" class="title">
				<span class="accessibility">The MacPorts Project</span>
			</a>
			<a href="/" title="MacPorts Project Statistics" class="subtitle">Statistics</a>
		</h1>
		<p class="accessibility">
			<a href="#content">Skip to Content</a>
		</p>
		<div id="header">
		</div>
		<div id="navigation">
			<dl>
				<dt>Statistics</dt>
				<dd>
					<ul>
						<li class="<%= 'selected' if current_page?(root_path) %>">
							<%= link_to "Home", root_path %>
						</li>
						<li class="<%= 'selected' if current_page?(:controller => 'os_statistics') %>">
							<%= link_to "System Statistics", os_statistics_path %>
						</li>
						<li class="<%= 'selected' if current_page?(:controller => 'installed_ports') %>">
							<%= link_to "Port Statistics", installed_ports_path %>
						</li>
					</ul>
				</dd>
				<dt>Browse Ports</dt>
				<dd>
					<ul>
						<li class="<%= 'selected' if current_page?(:controller => 'categories') %>">
							<%= link_to "By Category", categories_path %>
						</li>
						<li class="<%= 'selected' if current_page?(:controller => 'ports') %>">
							<%= link_to "Complete List", ports_path %>
						</li>
					</ul>
				</dd>
				<dt>About</dt>
				<dd>
					<ul>
						<li class="<%= 'selected' if current_page?(:controller => 'static', :action => 'faq') %>">
							<%= link_to "FAQ", :controller => 'static', :action => 'faq'  %>
						</li>
						<li class="<%= 'selected' if current_page?(:controller => 'static', :action => 'credits') %>">
							<%= link_to "Credits", :controller => 'static', :action => 'credits'  %>
						</li>
					</ul>
				</dd>
			</dl>
		</div>
		<div id="content">
			<%= yield %>
		</div>
		<div id="footer">
		</div>
	</body>
</html>