stats-server/config/routes.rb
StatsServer::Application.routes.draw do

  get "home/index"

  resources :submissions
  resources :os_statistics
  resources :installed_ports
  resources :categories, :only => [:index] do
    match '/ports/page/:page', :to => 'ports#index', :page => :page
    resources :ports, :only => [:index, :show]
  end

  match '/ports/page/:page', :to => 'ports#index', :page => :page
  resources :ports, :only => [:index, :search]
  match '/ports/search', :to => 'ports#search_generate', :as => :search_generate
  match '/ports/search/:criteria/:val/page/:page', :to => 'ports#search', :criteria => :criteria, :val => :val, :page => :page
  match '/ports/search/:criteria/:val', :to => 'ports#search', :criteria => :criteria, :val => :val, :as => :search

  root :to => 'home#index'
  match ':action' => 'static#:action'
end

stats-server/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :ports

	validates_presence_of :name
end

stats-server/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	caches_page :index
	cache_sweeper :category_sweeper, :only => [:create, :update, :destroy]

	def index
		@categories = Category.all(:order => 'name ASC')
	end
end

stats-server/app/helpers/categories_helper.rb
module CategoriesHelper
end

stats-server/app/views/categories/index.html.erb
<%= render :partial => '/partials/port_search' %>

<h2>Port Categories</h2>
<div id="categories">
	<% unless @categories.empty? %>
		<ul>
			<% @categories.each do |category| %>
				<li><%= link_to category.name, category_ports_path(category.id) %></li>
			<% end %>
		</ul>
	<% else %>
		<p>No categories found.</p>
	<% end %>
</div>